cmake_minimum_required(VERSION 3.10)

add_subdirectory(ComponentBase)
add_subdirectory(ControlFlow)
add_subdirectory(TransitionHandling)
add_subdirectory(ProductHandling)
add_subdirectory(DataModel)
add_subdirectory(DataProductBase)
add_subdirectory(Concurrency)
add_subdirectory(Base)
add_subdirectory(Utilities)
